Repository Synapxe-DNA/healthhub-content-optimization, pull requests merged in 2024-06, with the labels that each got.

#18 Kedro branch
  content-optimization/.telemetry
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/notebooks/tmp.ipynb
  content-optimization/session_store.db
  content-optimization/src/content_optimization/pipelines/data_processing/__init__.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
  content-optimization/tests/pipelines/data_processing/__init__.py
  content-optimization/tests/pipelines/data_processing/test_pipeline.py
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement

#22 added glove notebook with cos similarity metric
  notebooks/glove.ipynb
Labels: enhancement

#23 Updated .pre-commit-config
  .pre-commit-config.yaml
  notebooks/glove.ipynb
Labels: enhancement

#24 Added installation documentation for Poetry in README.md
  README.md
Labels: documentation

#26 Updated data_processing pipeline
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/docs/images/kedro-pipeline.png
  content-optimization/notebooks/preprocess.ipynb
  content-optimization/notebooks/tmp.ipynb
  content-optimization/pyproject.toml
  content-optimization/session_store.db
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
  content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
  content-optimization/stats.json
Labels: enhancement

#27 Improved data_processing pipeline
  content-optimization/.gitignore
  content-optimization/.telemetry
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/docs/images/kedro-pipeline.png
  content-optimization/notebooks/preprocess.ipynb
  content-optimization/session_store.db
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
  content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
  content-optimization/stats.json
Labels: enhancement

#28 Documentation for Kedro data_processing pipeline
  content-optimization/README.md
  content-optimization/data/01_raw/all_contents/.gitkeep
  content-optimization/data/02_intermediate/all_contents_extracted/.gitkeep
  content-optimization/data/02_intermediate/all_contents_processed/.gitkeep
  content-optimization/data/02_intermediate/all_extracted_text/.gitkeep
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Labels: documentation, enhancement

#31 Merge kedro-text-preprocess into kedro-branch
  content-optimization/README.md
  content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
Labels: documentation, enhancement

#32 Merge issac's changes
  content-optimization/README.md
  content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
Labels: documentation, enhancement

#34 Initialised Angular Frontend
  .gitignore
  frontend/README.md
  frontend/app/README.md
  frontend/app/angular.json
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/app/app.component.css
  frontend/app/src/app/app.component.html
  frontend/app/src/app/app.component.spec.ts
  frontend/app/src/app/app.component.ts
  frontend/app/src/app/app.config.ts
  frontend/app/src/app/app.routes.ts
  frontend/app/src/app/components/README.md
  frontend/app/src/app/pages/README.md
  frontend/app/src/app/pages/index/index.component.css
  frontend/app/src/app/pages/index/index.component.html
  frontend/app/src/app/pages/index/index.component.spec.ts
  frontend/app/src/app/pages/index/index.component.ts
  frontend/app/src/app/services/README.md
  frontend/app/src/assets/.gitkeep
  frontend/app/src/favicon.ico
  frontend/app/src/index.html
  frontend/app/src/main.ts
  frontend/app/src/styles.css
  frontend/app/tailwind.config.js
  frontend/app/tsconfig.app.json
  frontend/app/tsconfig.json
  frontend/app/tsconfig.spec.json
Labels: enhancement

#35 Edited function to flag articles for removal
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Labels: enhancement

#36 Merge changes from kedro-text-preprocess into kedro-branch
  Makefile
  content-optimization/README.md
  content-optimization/notebooks/extract_div.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
  notebooks/text_preprocessing.ipynb
Labels: bug, documentation, enhancement

#37 Kedro branch
  Makefile
  content-optimization/README.md
  content-optimization/notebooks/extract_div.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
  notebooks/text_preprocessing.ipynb
Labels: bug, documentation, enhancement

#38 PR for MongoDB Docker Setup
  .gitignore
  Makefile
  docker/Dockercompose.yaml
  docker/README.md
  docker/dockercompose.env.sample
Labels: enhancement

#39 edited runner notebook to incorporate reading of sbert_embedding scores in xlsx
  notebooks/runner.ipynb
  notebooks/scores_eval.ipynb
Labels: enhancement

#41 Kedro branch
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  docker/README.md
  docker/dockercompose.env.sample
Labels: bug

#44 Merge changes from `kedro-bug` to `kedro-branch`
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
Labels: bug

#47 Setup barebones structure of backend
  backend/app/EndpointDocs.yaml
  backend/app/README.md
  backend/app/app/__init__.py
  backend/app/app/main.py
  backend/app/app/routes/README.md
  backend/app/app/routes/__init__.py
  backend/app/app/routes/articles/__init__.py
  backend/app/app/routes/articles/article_router.py
  backend/app/app/routes/check/__init__.py
  backend/app/app/routes/check/check_router.py
  backend/app/app/routes/clusters/__init__.py
  backend/app/app/routes/clusters/cluster_router.py
  backend/app/app/routes/harmonise/__init__.py
  backend/app/app/routes/harmonise/harmonise_router.py
  backend/app/app/routes/optimise/__init__.py
  backend/app/app/routes/optimise/optimise_router.py
  backend/app/app/utils/__init__.py
  backend/app/app/utils/app_builder/README.md
  backend/app/app/utils/app_builder/__init__.py
  backend/app/app/utils/app_builder/app_builer.py
  backend/app/poetry.lock
  backend/app/pyproject.toml
  backend/app/tests/__init__.py
Labels: enhancement

#49 Improved `extract_links` and `extract_headers` functions
  content-optimization/notebooks/extract_div.ipynb
  content-optimization/notebooks/preprocess.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/preprocess.py
Labels: enhancement

#51 Updated data_processing pipeline
  content-optimization/README.md
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/data/02_intermediate/all_contents_standardized/.gitkeep
  content-optimization/docs/images/kedro-pipeline.png
  content-optimization/notebooks/columns.ipynb
  content-optimization/notebooks/extract.ipynb
  content-optimization/notebooks/preprocess.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/columns.py
  content-optimization/src/content_optimization/pipelines/data_processing/extract.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
Labels: documentation, enhancement

#50 Update construct_graph.ipynb to exclude other contributors
  notebooks/construct_graph.ipynb
  notebooks/runner.ipynb
Labels: enhancement

#52 Merge changes to data processing pipeline to main branch
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/src/content_optimization/pipelines/data_processing/columns.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/utils/__init__.py
  content-optimization/src/content_optimization/utils/columns.py
  content-optimization/src/content_optimization/utils/extract.py
Labels: enhancement

#54 Merge `kedro-text-process` into `main`
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/utils/extract.py
Labels: bug, enhancement
