Repository Synapxe-DNA/healthhub-content-optimization, pull requests merged in 2024-10, with the labels that each got.

#194 Added raw data to DVC
  .dvc/config
  content-optimization/.env.sample
  content-optimization/data/01_raw/.gitignore
  content-optimization/data/01_raw/all_contents.dvc
  content-optimization/data/01_raw/google_analytics.xlsx.dvc
  content-optimization/data/01_raw/missing_contents.dvc
  content-optimization/scripts/get_raw_data.ps1
  content-optimization/scripts/get_raw_data.sh
  content-optimization/scripts/setup_dvc.ps1
  content-optimization/scripts/setup_dvc.sh
Labels: enhancement

#197 Updated and cleaned up multiple READMEs
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  article-harmonisation/README.md
  backend/app/README.md
  content-optimization/README.md
  content-optimization/conf/README.md
  content-optimization/docs/MERGED_DATA_INFO.md
  content-optimization/docs/PROCESSED_DATA_INFO.md
  content-optimization/docs/SETTING_UP_AZURE.md
  content-optimization/docs/SETTING_UP_NEO4J.md
  content-optimization/docs/images/dvc.png
  content-optimization/docs/images/test.png
  content-optimization/src/content_optimization/pipelines/azure_rag/llm_extraction.py
  docker/README.md
  frontend/app/src/app/services/README.md
Labels: documentation, enhancement

#198 Minor edits to README
  content-optimization/README.md
  content-optimization/docs/MERGED_DATA_INFO.md
  content-optimization/docs/PROCESSED_DATA_INFO.md
  content-optimization/docs/images/dvc.png
  content-optimization/docs/images/test.png
Labels: documentation

#199 Added ground truth data to DVC
  .dvc/config
  content-optimization/conf/base/catalog.yml
  content-optimization/data/01_raw/ground_truth.xlsx.dvc
  content-optimization/docs/SETTING_UP_NEO4J.md
  content-optimization/scripts/get_raw_data.sh
  content-optimization/scripts/setup_dvc.ps1
  content-optimization/scripts/setup_dvc.sh
Labels: enhancement

#204 Updated dvc files for Integration with Azure
  .dvc/config
  content-optimization/.env.sample
  content-optimization/README.md
  content-optimization/scripts/get_raw_data.ps1
  content-optimization/scripts/setup_dvc.ps1
  content-optimization/scripts/setup_dvc.sh
Labels: enhancement

#205 Updated scripts for DVC
  content-optimization/scripts/setup_dvc.ps1
  content-optimization/scripts/setup_dvc.sh
Labels: enhancement
