Repository Synapxe-DNA/healthhub-content-optimization, pull requests merged in 2024-08, with the labels that each got.

#138 Article harmonisation jc
  article-harmonisation/agents/models.py
  article-harmonisation/agents/prompts.py
  article-harmonisation/agents/prompts_archive.py
  article-harmonisation/harmonisation.py
  article-harmonisation/main.py
  article-harmonisation/utils/formatters.py
Labels: bug, enhancement

#142 Added blacklisted articles from clustering
  CHANGELOG.md
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
Labels: enhancement

#143 Article harmonisation jc
  article-harmonisation/agents/enums.py
  article-harmonisation/agents/models.py
  article-harmonisation/agents/prompts.py
  article-harmonisation/checks.py
  article-harmonisation/harmonisation.py
  article-harmonisation/states/definitions.py
  article-harmonisation/utils/formatters.py
Labels: bug, documentation, enhancement

#144 Kedro text preprocess
  content-optimization/notebooks/evaluate_duplicates.ipynb
  content-optimization/notebooks/evaluate_ia_mappings.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
Labels: enhancement

#145 Article harmonisation ij
  article-harmonisation/agents/models.py
  article-harmonisation/agents/prompts.py
  article-harmonisation/agents/prompts_archive.py
  article-harmonisation/checks.py
  article-harmonisation/notebooks/compare.ipynb
  article-harmonisation/notebooks/evaluate_word_count.ipynb
  article-harmonisation/states/definitions.py
  article-harmonisation/utils/formatters.py
Labels: enhancement

#146 Modify to flag recipe first before duplicated URL
  CHANGELOG.md
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
Labels: bug

#148 Update README.md and CHANGLOG.md with clustering information
  CHANGELOG.md
  content-optimization/README.md
  content-optimization/docs/images/kedro-pipeline.png
  content-optimization/requirements.txt
Labels: documentation

#151 Article harmonisation jc
  article-harmonisation/.env.example
  article-harmonisation/agents/models.py
  article-harmonisation/agents/prompts.py
  article-harmonisation/agents/prompts_archive.py
  article-harmonisation/config.py
  article-harmonisation/docs/images/article_rewriting_flow.png
  article-harmonisation/docs/images/optimisation_checks_flow.png
  article-harmonisation/harmonisation.py
  article-harmonisation/main.py
  article-harmonisation/main_harmonisation.py
  article-harmonisation/notebooks/readability_scores.ipynb
  article-harmonisation/states/definitions.py
  article-harmonisation/utils/evaluations.py
  article-harmonisation/utils/excel_extractor.py
  article-harmonisation/utils/formatters.py
Labels: bug, documentation, enhancement

#156 Article harmonisation ij
  article-harmonisation/agents/models.py
  article-harmonisation/agents/prompts.py
  article-harmonisation/checks.py
  article-harmonisation/states/definitions.py
  article-harmonisation/utils/formatters.py
Labels: bug, enhancement

#157 Kedro text preprocess
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
Labels: documentation, enhancement

#158 Article harmonisation jc
  article-harmonisation/README.md
  article-harmonisation/agents/models.py
  article-harmonisation/agents/prompts.py
  article-harmonisation/harmonisation.py
  article-harmonisation/main_harmonisation.py
  article-harmonisation/states/definitions.py
  article-harmonisation/utils/excel_extractor.py
  article-harmonisation/utils/formatters.py
Labels: bug, documentation, enhancement

#162 Article harmonisation ij
  article-harmonisation/README.md
  article-harmonisation/checks.py
  article-harmonisation/utils/formatters.py
Labels: bug, documentation, enhancement

#163 Article harmonisation ij
  article-harmonisation/README.md
  article-harmonisation/checks.py
  article-harmonisation/data/article_rewriting/.gitkeep
  article-harmonisation/utils/formatters.py
Labels: bug, documentation

#171 Article harmonisation
  article-harmonisation/README.md
  backend/app/README.md
  notebooks/text_preprocessing.ipynb
Labels: documentation, enhancement

#175 Article harmonisation jc
  article-harmonisation/README.md
  article-harmonisation/main_harmonisation.py
  article-harmonisation/states/definitions.py
  article-harmonisation/utils/excel_extractor.py
Labels: documentation, enhancement

#176 Article harmonisation
  article-harmonisation/README.md
  article-harmonisation/main_harmonisation.py
  article-harmonisation/states/definitions.py
  article-harmonisation/utils/excel_extractor.py
Labels: documentation, enhancement

#178 Kedro text preprocess
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Labels: documentation
