Repository Synapxe-DNA/healthhub-content-optimization, pull requests merged in 2024-07, with the labels that each got.

#56 Merge `datasheet` into `main`
  content-optimization/README.md
  content-optimization/src/content_optimization/utils/extract.py
Labels: bug, documentation

#57 Extended flagging feature to flag by word count
  content-optimization/README.md
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/notebooks/presentation.ipynb
  content-optimization/notebooks/word_count.ipynb
  content-optimization/requirements.txt
  content-optimization/src/content_optimization/datasets/__init__.py
  content-optimization/src/content_optimization/datasets/plotly.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
Labels: enhancement

#60 Modified presentation.ipynb
  CHANGELOG.md
  content-optimization/notebooks/presentation.ipynb
Labels: enhancement

#61 Major refactor processing utils code to flag articles by type
  content-optimization/notebooks/presentation.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
  content-optimization/src/content_optimization/utils/__init__.py
  content-optimization/src/content_optimization/utils/columns.py
Labels: enhancement

#62 Added `feature_engineering` pipeline
  content-optimization/README.md
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_data_science.yml
  content-optimization/conf/base/parameters_feature_engineering.yml
  content-optimization/data/02_intermediate/all_contents_standardized/.gitkeep
  content-optimization/data/02_intermediate/all_extracted_text/.gitkeep
  content-optimization/docs/images/kedro-pipeline.png
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_science/nodes.py
  content-optimization/src/content_optimization/pipelines/data_science/pipeline.py
  content-optimization/src/content_optimization/pipelines/feature_engineering/__init__.py
  content-optimization/src/content_optimization/pipelines/feature_engineering/nodes.py
  content-optimization/src/content_optimization/pipelines/feature_engineering/pipeline.py
  content-optimization/tests/pipelines/data_science/__init__.py
  content-optimization/tests/pipelines/feature_engineering/__init__.py
  content-optimization/tests/pipelines/feature_engineering/test_pipeline.py
Labels: documentation, enhancement

#63 Merge `Kedro text preprocess` into `main`
  CHANGELOG.md
  content-optimization/notebooks/evaluate_text_extraction.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Labels: bug, documentation, enhancement

#65 Update README.md
  README.md
Labels: documentation

#67 Update Main Page Cluster and integrate with backend
  backend/app/app/scripts/populate_mongo_mock/generators/mocker.py
  backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py
  backend/app/poetry.lock
  frontend/app/src/app/app.component.html
  frontend/app/src/app/components/cluster/main-cluster-filter-sort/main-cluster-filter-sort.component.html
  frontend/app/src/app/components/cluster/main-cluster-filter-sort/main-cluster-filter-sort.component.ts
  frontend/app/src/app/components/cluster/main-cluster-filter-sort/main-cluster-filter.component.css
  frontend/app/src/app/components/cluster/main-cluster-filter-sort/main-cluster-filter.component.html
  frontend/app/src/app/components/cluster/main-cluster-filter-sort/main-cluster-filter.component.spec.ts
  frontend/app/src/app/components/cluster/main-cluster-filter-sort/main-cluster-filter.component.ts
  frontend/app/src/app/components/cluster/main-cluster-sideview/main-cluster-sideview.component.css
  frontend/app/src/app/components/cluster/main-cluster-sideview/main-cluster-sideview.component.html
  frontend/app/src/app/components/cluster/main-cluster-sideview/main-cluster-sideview.component.spec.ts
  frontend/app/src/app/components/cluster/main-cluster-sideview/main-cluster-sideview.component.ts
  frontend/app/src/app/components/cluster/main-cluster-sort/main-cluster-sort.component.css
  frontend/app/src/app/components/cluster/main-cluster-sort/main-cluster-sort.component.html
  frontend/app/src/app/components/cluster/main-cluster-sort/main-cluster-sort.component.spec.ts
  frontend/app/src/app/components/cluster/main-cluster-sort/main-cluster-sort.component.ts
  frontend/app/src/app/components/cluster/main-cluster-table/main-cluster-table.component.html
  frontend/app/src/app/components/cluster/main-cluster-table/main-cluster-table.component.ts
  frontend/app/src/app/components/cluster/status-bar/status-bar.component.css
  frontend/app/src/app/components/cluster/status-bar/status-bar.component.html
  frontend/app/src/app/components/cluster/status-bar/status-bar.component.spec.ts
  frontend/app/src/app/components/cluster/status-bar/status-bar.component.ts
  frontend/app/src/app/components/filter-popup/filter-popup.component.html
  frontend/app/src/app/components/filter-popup/filter-popup.component.ts
  frontend/app/src/app/environments/environment.types.ts
  frontend/app/src/app/pages/clusters/clusters.component.html
  frontend/app/src/app/pages/clusters/clusters.component.ts
  frontend/app/src/app/services/cluster/cluster.service.ts
  frontend/app/src/app/types/data/article.types.ts
  frontend/app/src/app/types/data/cluster.types.ts
  frontend/app/src/app/types/data/edge.types.ts
  frontend/app/src/app/types/filters.types.ts
  frontend/app/src/assets/test.json
Labels: enhancement

#68 Create lint-frontend.yml
  .github/workflows/lint-frontend.yml
Labels: enhancement

#70 Modfied feature_engineering pipeline
  content-optimization/README.md
  content-optimization/conf/base/catalog.yml
  content-optimization/conf/base/parameters_feature_engineering.yml
  content-optimization/notebooks/evaluate_text_extraction.ipynb
  content-optimization/notebooks/extractor.ipynb
  content-optimization/src/content_optimization/pipelines/feature_engineering/nodes.py
  content-optimization/src/content_optimization/pipelines/feature_engineering/pipeline.py
Labels: bug, documentation, enhancement

#74 Merge new text extraction pipeline into main
  .gitignore
  CHANGELOG.md
  content-optimization/README.md
  content-optimization/notebooks/evaluate_text_extraction.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Labels: bug, documentation, enhancement

#64 Added populate_mongo to populate real data in mongodb
  .gitignore
  backend/app/README.md
  backend/app/app/data/.gitkeep
  backend/app/app/scripts/populate_mongo/__init__.py
  backend/app/app/scripts/populate_mongo/db_populator.py
  backend/app/app/scripts/populate_mongo/main.py
  backend/app/app/utils/db_connector/mongo_connector/beanie_documents.py
  backend/app/poetry.lock
  backend/app/pyproject.toml
  docker/README.md
Labels: documentation, enhancement

#77 Added new arguments to extract_keywords node
  CHANGELOG.md
  content-optimization/conf/base/parameters_feature_engineering.yml
  content-optimization/src/content_optimization/pipelines/feature_engineering/nodes.py
  content-optimization/src/content_optimization/pipelines/feature_engineering/pipeline.py
Labels: enhancement

#78 Merge minor changes to data processing pipeline
  CHANGELOG.md
  README.md
  content-optimization/README.md
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
Labels: bug, documentation

#79 Webapp use real data
  backend/app/app/models/article.py
  backend/app/app/scripts/populate_mongo/db_populator.py
  backend/app/app/utils/db_connector/mongo_connector/beanie_documents.py
  backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py
  backend/app/app/utils/db_connector/mongo_connector/mongo_connector_injector.py
  backend/app/poetry.lock
  backend/app/pyproject.toml
  frontend/app/src/styles.css
Labels: enhancement

#80 Bugfix -- Backend BSON import errors
  backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py
  backend/app/poetry.lock
  backend/app/pyproject.toml
Labels: bug

#81 Created `clustering` pipeline + Updated `CHANGELOG.md`
  CHANGELOG.md
  content-optimization/conf/base/parameters_clustering.yml
  content-optimization/src/content_optimization/pipelines/clustering/__init__.py
  content-optimization/src/content_optimization/pipelines/clustering/nodes.py
  content-optimization/src/content_optimization/pipelines/clustering/pipeline.py
  content-optimization/tests/pipelines/clustering/__init__.py
  content-optimization/tests/pipelines/clustering/test_pipeline.py
Labels: documentation, enhancement

#82 Update text processing pipeline to handle minor edge cases
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
Labels: bug

#83 Added in subgroup functionality to second page
  frontend/app/package-lock.json
  frontend/app/package.json
  frontend/app/src/app/app.config.ts
  frontend/app/src/app/components/accordian/accordion.component.css
  frontend/app/src/app/components/accordian/accordion.component.html
  frontend/app/src/app/components/accordian/accordion.component.spec.ts
  frontend/app/src/app/components/accordian/accordion.component.ts
  frontend/app/src/app/components/article-list-item/article-list-item.component.css
  frontend/app/src/app/components/article-list-item/article-list-item.component.html
  frontend/app/src/app/components/article-list-item/article-list-item.component.spec.ts
  frontend/app/src/app/components/article-list-item/article-list-item.component.ts
  frontend/app/src/app/components/article/article-more/article-more.component.css
  frontend/app/src/app/components/article/article-more/article-more.component.html
  frontend/app/src/app/components/article/article-more/article-more.component.spec.ts
  frontend/app/src/app/components/article/article-more/article-more.component.ts
  frontend/app/src/app/components/article/article.component.html
  frontend/app/src/app/components/article/article.component.ts
  frontend/app/src/app/components/cluster/cluster-table/cluster-table.component.html
  frontend/app/src/app/components/cluster/cluster-table/cluster-table.component.ts
  frontend/app/src/app/pages/cluster-id/cluster-id.component.html
  frontend/app/src/app/pages/cluster-id/cluster-id.component.ts
  frontend/app/src/app/pipes/date/date.pipe.spec.ts
  frontend/app/src/app/pipes/date/date.pipe.ts
  frontend/app/src/app/types/data/article.types.ts
  frontend/app/src/app/utiles/group-manager.ts
Labels: enhancement

#84 Frontend S2F8 -- Added card on hover over article
  frontend/app/src/app/components/article-list-item/article-list-item.component.html
  frontend/app/src/app/components/article-list-item/article-list-item.component.ts
  frontend/app/src/app/components/article/article-card/article-card.component.css
  frontend/app/src/app/components/article/article-card/article-card.component.html
  frontend/app/src/app/components/article/article-card/article-card.component.spec.ts
  frontend/app/src/app/components/article/article-card/article-card.component.ts
  frontend/app/src/app/components/article/article-list-item/article-list-item.component.css
  frontend/app/src/app/components/article/article-list-item/article-list-item.component.html
  frontend/app/src/app/components/article/article-list-item/article-list-item.component.spec.ts
  frontend/app/src/app/components/article/article-list-item/article-list-item.component.ts
  frontend/app/src/app/components/article/article.component.ts
  frontend/app/src/app/pages/cluster-id/cluster-id.component.ts
Labels: enhancement

#90 Improve Text Processing Pipeline
  content-optimization/README.md
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
Labels: bug, documentation, enhancement

#94 Added unit tests and integration tests for `data_processing` pipeline
  content-optimization/.gitignore
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/notebooks/columns.ipynb
  content-optimization/notebooks/extractor.ipynb
  content-optimization/requirements.txt
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
  content-optimization/tests/data/01_raw/.gitkeep
  content-optimization/tests/data/02_intermediate/.gitkeep
  content-optimization/tests/data/03_primary/.gitkeep
  content-optimization/tests/data/04_feature/.gitkeep
  content-optimization/tests/data/05_model_input/.gitkeep
  content-optimization/tests/data/06_models/.gitkeep
  content-optimization/tests/data/07_model_output/.gitkeep
  content-optimization/tests/data/08_reporting/.gitkeep
  content-optimization/tests/pipelines/data_processing/conftest.py
  content-optimization/tests/pipelines/data_processing/test_nodes.py
  content-optimization/tests/pipelines/data_processing/test_pipeline.py
  content-optimization/tests/test_run.py
Labels: bug, enhancement

#95 Integrated `make test` to test kedro pipeline from root
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  README.md
  content-optimization/pyproject.toml
  content-optimization/tests/pipelines/data_processing/conftest.py
  content-optimization/tests/pipelines/data_processing/test_nodes.py
  content-optimization/tests/pipelines/data_processing/test_pipeline.py
  run_tests.py
  script.py
Labels: documentation, enhancement

#97 Added unit tests and integration tests for `feature_engineering` pipeline
  content-optimization/conf/base/parameters_feature_engineering.yml
  content-optimization/tests/pipelines/clustering/test_nodes.py
  content-optimization/tests/pipelines/conftest.py
  content-optimization/tests/pipelines/data_processing/test_nodes.py
  content-optimization/tests/pipelines/feature_engineering/test_nodes.py
  content-optimization/tests/pipelines/feature_engineering/test_pipeline.py
Labels: enhancement

#98 Added `pytest.mark.parametrize`
  content-optimization/tests/pipelines/data_processing/test_nodes.py
  content-optimization/tests/pipelines/feature_engineering/test_nodes.py
Labels: enhancement

#103 Updated `data_processing pipeline` to whitelist articles
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/notebooks/presentation.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
  content-optimization/tests/pipelines/conftest.py
  content-optimization/tests/pipelines/data_processing/test_nodes.py
Labels: documentation, enhancement

#104 Fix -- Updated angular versions to update vuln dev dep
  frontend/app/package-lock.json
  frontend/app/package.json
Labels: bug

#100 Article harmonisation
  CHANGELOG.md
  article-harmonisation/README.md
  article-harmonisation/docs/images/Article harmonisation flow 1.png
  article-harmonisation/harmonisation.py
  article-harmonisation/models.py
  article-harmonisation/prompt.py
  article-harmonisation/requirements.txt
  content-optimization/notebooks/evaluate_text_extraction.ipynb
Labels: documentation, enhancement

#105 Webapp update schema lyndon
  backend/app/app/interfaces/db_connector_types.py
  backend/app/app/models/group.py
  backend/app/app/models/job.py
  backend/app/app/models/job_combine.py
  backend/app/app/models/job_ignore.py
  backend/app/app/scripts/populate_mongo_mock/generators/mocker.py
  backend/app/app/utils/db_connector/mongo_connector/beanie_documents.py
  backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py
Labels: enhancement

#106 Merge main into webapp
  .github/workflows/lint.yml
  .github/workflows/publish-kedro-viz.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  README.md
  article-harmonisation/README.md
  article-harmonisation/docs/images/Article harmonisation flow 1.png
  article-harmonisation/harmonisation.py
  article-harmonisation/models.py
  article-harmonisation/prompt.py
  article-harmonisation/requirements.txt
  content-optimization/.gitignore
  content-optimization/README.md
  content-optimization/conf/base/parameters_clustering.yml
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/conf/base/parameters_feature_engineering.yml
  content-optimization/notebooks/columns.ipynb
  content-optimization/notebooks/evaluate_text_extraction.ipynb
  content-optimization/notebooks/extractor.ipynb
  content-optimization/notebooks/presentation.ipynb
  content-optimization/pyproject.toml
  content-optimization/requirements.txt
  content-optimization/src/content_optimization/pipelines/clustering/__init__.py
  content-optimization/src/content_optimization/pipelines/clustering/nodes.py
  content-optimization/src/content_optimization/pipelines/clustering/pipeline.py
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
  content-optimization/src/content_optimization/pipelines/feature_engineering/nodes.py
  content-optimization/src/content_optimization/pipelines/feature_engineering/pipeline.py
  content-optimization/tests/data/01_raw/.gitkeep
  content-optimization/tests/data/02_intermediate/.gitkeep
  content-optimization/tests/data/03_primary/.gitkeep
  content-optimization/tests/data/04_feature/.gitkeep
  content-optimization/tests/data/05_model_input/.gitkeep
  content-optimization/tests/data/06_models/.gitkeep
  content-optimization/tests/data/07_model_output/.gitkeep
  content-optimization/tests/data/08_reporting/.gitkeep
  content-optimization/tests/pipelines/clustering/__init__.py
  content-optimization/tests/pipelines/clustering/test_nodes.py
  content-optimization/tests/pipelines/clustering/test_pipeline.py
  content-optimization/tests/pipelines/conftest.py
  content-optimization/tests/pipelines/data_processing/test_nodes.py
  content-optimization/tests/pipelines/data_processing/test_pipeline.py
  content-optimization/tests/pipelines/feature_engineering/test_nodes.py
  content-optimization/tests/pipelines/feature_engineering/test_pipeline.py
  content-optimization/tests/test_run.py
  frontend/app/package-lock.json
  frontend/app/package.json
  requirements.txt
  run_tests.py
  script.py
Labels: enhancement

#107 Added checks to prevent duplication of the articles having the same type
  backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py
Labels: enhancement

#108 Integrated code to flag for recipe articles
  content-optimization/notebooks/presentation.ipynb
  content-optimization/notebooks/recipes.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
Labels: enhancement

#101 Added the content body of selected articles with `Excel Errors` back into the dataset
  CHANGELOG.md
  content-optimization/README.md
  content-optimization/conf/base/catalog.yml
  content-optimization/data/01_raw/missing_contents/.gitkeep
  content-optimization/docs/images/kedro-pipeline.png
  content-optimization/notebooks/multilingual_text.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/pipeline.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
  content-optimization/tests/data/01_raw/missing_contents/.gitkeep
  content-optimization/tests/pipelines/conftest.py
  content-optimization/tests/pipelines/data_processing/test_nodes.py
Labels: documentation, enhancement

#109 Fixed mulilingual flagging & shifted extraction code in add_contents
  CHANGELOG.md
  content-optimization/data/01_raw/missing_contents/.gitkeep
  content-optimization/notebooks/multilingual_text.ipynb
  content-optimization/notebooks/presentation.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/src/content_optimization/pipelines/data_processing/utils.py
Labels: bug, documentation

#110 Update typos in db and mongo connector
  backend/app/app/interfaces/db_connector_types.py
  backend/app/app/utils/db_connector/mongo_connector/mongo_connector.py
Labels: bug

#111 Extended `catalog.yml` to store recipes data + Added TODO in `README.md`
  content-optimization/README.md
  content-optimization/conf/base/catalog.yml
  content-optimization/notebooks/recipes.ipynb
Labels: documentation, enhancement

#112 Article harmonisation issac
  article-harmonisation/README.md
  article-harmonisation/models.py
  article-harmonisation/prompt.py
  article-harmonisation/prompts.py
Labels: bug, documentation, enhancement

#114 Article harmonisation issac
  article-harmonisation/README.md
  article-harmonisation/evaluations.py
  article-harmonisation/requirements.txt
Labels: documentation, enhancement

#115 GenAI algorithm Article Harmonisation update
  article-harmonisation/.env.example
  article-harmonisation/README.md
  article-harmonisation/evaluations.py
  article-harmonisation/harmonisation.py
  article-harmonisation/models.py
  article-harmonisation/prompt.py
  article-harmonisation/prompts.py
  article-harmonisation/requirements.txt
Labels: bug, documentation, enhancement

#116 Major update and optimizations to `pre-commit-hooks` and GitHub Actions
  .gitattributes
  .github/workflows/lint-frontend.yml
  .github/workflows/lint.yml
  .github/workflows/run-checks.yml
  .markdownlint.jsonc
  .pre-commit-config.yaml
  README.md
  article-harmonisation/.env.example
  article-harmonisation/README.md
  backend/app/EndpointDocs.yaml
  backend/app/README.md
  backend/app/app/routes/README.md
  backend/app/app/utils/app_builder/README.md
  content-optimization/README.md
  content-optimization/conf/README.md
  content-optimization/notebooks/evaluate_text_extraction.ipynb
  content-optimization/src/content_optimization/settings.py
  docker/Dockercompose.yaml
  docker/README.md
  frontend/README.md
  frontend/app/angular.json
  frontend/app/src/app/components/README.md
  frontend/app/src/app/pages/README.md
  frontend/app/src/app/services/README.md
  frontend/app/src/styles.css
  frontend/app/tsconfig.app.json
  frontend/app/tsconfig.json
  frontend/app/tsconfig.spec.json
  notebooks/construct_graph.ipynb
  notebooks/doc2vec.ipynb
  notebooks/emb_sim_statistical.ipynb
  notebooks/text_preprocessing.ipynb
Labels: enhancement

#117 Updated `pre-commit-config`
  .pre-commit-config.yaml
Labels: enhancement

#118 Fixed prettier `toml` plugin
  .github/workflows/run-checks.yml
  .pre-commit-config.yaml
Labels: bug

#120 Bug Fixes for missing content in catalog.yml
  content-optimization/conf/base/catalog.yml
Labels: bug

#121 Added whitelisted articles from recipes + BERTopic works
  content-optimization/conf/base/parameters_data_processing.yml
  content-optimization/notebooks/bertopic.ipynb
Labels: enhancement

#119 Article harmonisation ij
  article-harmonisation/.env.example
  article-harmonisation/README.md
  article-harmonisation/app.py
  article-harmonisation/harmonisation.py
  article-harmonisation/requirements.txt
Labels: bug, documentation, enhancement

#123 Article harmonisation ij
  article-harmonisation/.env.example
  article-harmonisation/README.md
  article-harmonisation/app.py
  article-harmonisation/data/.gitkeep
  article-harmonisation/harmonisation.py
  article-harmonisation/models.py
  article-harmonisation/notebooks/calculate_tokens.ipynb
  article-harmonisation/notebooks/readability_scores.ipynb
  article-harmonisation/requirements.txt
  article-harmonisation/utils.py
  article-harmonisation/utils/__init__.py
  article-harmonisation/utils/arize-phoenix.py
  article-harmonisation/utils/evaluations.py
  content-optimization/notebooks/evaluate_text_extraction.ipynb
Labels: bug, documentation, enhancement

#125 Merge Image Extraction Pipeline into `main`
  CHANGELOG.md
  content-optimization/README.md
  content-optimization/notebooks/check_image_links.ipynb
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
  content-optimization/tests/pipelines/data_processing/test_nodes.py
Labels: documentation, enhancement

#127 Added new column for extracted_raw_html_tables
  CHANGELOG.md
  content-optimization/README.md
  content-optimization/src/content_optimization/pipelines/data_processing/extractor.py
  content-optimization/src/content_optimization/pipelines/data_processing/nodes.py
Labels: documentation, enhancement
